project_id = "ftadmxcxzhptngqbbqpk"

[functions.seed-admin]
verify_jwt = false

[functions.reset-institution-admin-password]
verify_jwt = true

[functions.create-institution-admin]
verify_jwt = true

[functions.create-student-user]
verify_jwt = true
